-- Hyprland configuration (Lua) — https://wiki.hypr.land/Configuring/Start/

hl.config({ autogenerated =false })

-- ═══════════════════════════════════════════════════════════════
-- SINGLE CONSOLIDATED STARTUP BLOCK - ALL COMMANDS HERE
-- ═══════════════════════════════════════════════════════════════
hl.on("hyprland.start", function()
	-- Environment setup
	hl.exec_cmd("dbus-update-activation-environment --systemd --all")
	hl.exec_cmd("systemctl --user start graphical-session.target")
	hl.exec_cmd("systemctl --user start hyprland-session.target")

	-- Load plugins (dynamic-cursors)
	-- hl.exec_cmd("hyprpm reload -n")
	-- Dark mode on launch
	--hl.exec_cmd('gsettings set org.gnome.desktop.interface color-scheme "prefer-dark"')
	--hl.exec_cmd('gsettings set org.gnome.desktop.interface gtk-theme "adw-gtk3-dark"')
	
	-- Load hyprshade shader - VIBRANCE
	hl.exec_cmd("hyprshade on vibrance")
	hl.exec_cmd("noctalia")

end)
-- ═══════════════════════════════════════════════════════════════

-- INPUT CONFIGURATION
hl.config({
	input = {
		kb_layout = "us,ara",
		kb_variant = "",
		-- Arabic layout switch with Scroll Lock modifier
		kb_options = "grp:alt_shift_toggle,scrolllock:mod3",
		numlock_by_default = true,
		follow_mouse = 0,
		touchpad = {
			tap_to_click = true,
			natural_scroll = true,
		},
	},
	general = {
		gaps_in = 5,
		gaps_out = 5,
		border_size = 2,
		layout = "dwindle",
	},
	decoration = {
		rounding = 12,
		active_opacity = 1.0,
		inactive_opacity = 1.0,
		shadow = {
			enabled = true,
			range = 30,
			render_power = 5,
			offset = "0 5",
			color = "rgba(00000070)",
		},
	},
	misc = {
		disable_hyprland_logo = true,
		disable_splash_rendering = true,
	},
	dwindle = {
		preserve_split = true,
	},
	master = {
		mfact = 0.5,
	},
})

-- ANIMATIONS
hl.animation({ leaf = "windowsIn", enabled = false, speed = 3, bezier = "default" })
hl.animation({ leaf = "windowsOut", enabled =false, speed = 3, bezier = "default" })
hl.animation({ leaf = "workspaces", enabled =false, speed = 5, bezier = "default" })
hl.animation({ leaf = "windowsMove", enabled =false, speed = 4, bezier = "default" })
hl.animation({ leaf = "fade", enabled = false, speed = 3, bezier = "default" })
hl.animation({ leaf = "border", enabled = true, speed = 3, bezier = "default" })

-- WINDOW RULES
hl.window_rule({ match = { class = "^(org\\.wezfurlong\\.wezterm)$" }, tile = true })
hl.window_rule({ match = { class = "^(org\\.gnome\\.)" }, rounding = 12 })
hl.window_rule({ match = { class = "^(gnome-control-center)$" }, tile = true })
hl.window_rule({ match = { class = "^(pavucontrol)$" }, tile = true })
hl.window_rule({ match = { class = "^(nm-connection-editor)$" }, tile = true })
hl.window_rule({ match = { class = "^(org\\.gnome\\.Calculator)$" }, float = true })
hl.window_rule({ match = { class = "^(gnome-calculator)$" }, float = true })
hl.window_rule({ match = { class = "^(galculator)$" }, float = true })
hl.window_rule({ match = { class = "^(blueman-manager)$" }, float = true })
hl.window_rule({ match = { class = "^(org\\.gnome\\.Nautilus)$" }, float = true })
hl.window_rule({ match = { class = "^(xdg-desktop-portal)$" }, float = true })
hl.window_rule({
	match = { class = "^(steam)$", title = "^(notificationtoasts)" },
	no_initial_focus = true,
	pin = true,
})
hl.window_rule({
	match = { class = "^(firefox)$", title = "^(Picture-in-Picture)$" },
	float = true,
})
hl.window_rule({ match = { class = "^(zoom)$" }, float = true })

-- LAYER RULES
hl.layer_rule({ match = { namespace = "^(quickshell)$" }, no_anim = true })
hl.layer_rule({ match = { namespace = "^dms:.*" }, no_anim = true })

-- HYPRBARS CONFIGURATION
hyprbars = {
    button = {
        color = "rgb(f6d014)",
        size = 12,
        action = "hyprctl dispatch exec ~/.local/bin/hypr-minimize.sh"
    }
}

-- REQUIRE CUSTOM MODULES
require("dms.colors")
require("dms.outputs")
require("dms.layout")
require("dms.cursor")
require("dms.binds")
require("dms.binds-user")
require("dms.windowrules")

--------------

hl.on("hyprland.start", function()
	-- Force Qt apps (like VirtualBox) to run via XWayland to avoid black screen rendering issues
	hl.exec_cmd("hyprctl setenv QT_QPA_PLATFORM xcb")

	-- Environment setup
	hl.exec_cmd("dbus-update-activation-environment --systemd --all")
	hl.exec_cmd("systemctl --user start graphical-session.target")
	hl.exec_cmd("systemctl --user start hyprland-session.target")
	
	-- Load hyprshade shader - VIBRANCE
	hl.exec_cmd("hyprshade on vibrance")
	hl.exec_cmd("noctalia")
end)


------


if hl.plugin.dynamic_cursors then
	hl.config { plugin = { dynamic_cursors = {

		enabled = true,

		mode = "none",

		shake = {
			enabled = true,
			threshold = 4.0,  -- higher = less sensitive (default 6.0)
			base = 4.0,        -- starting size multiplier when shaking
			speed = 2.0,       -- how fast it grows while shaking
			limit = 4.0,       -- max size multiplier
			timeout = 500,     -- ms before it shrinks back
			effects = false,
		},
	}}}
end


------

local function toggle_minimize()
    local win = hl.get_active_window()
    if not win then return end

    local ws_name = win.workspace and win.workspace.name or ""

    if ws_name == "special:minimize" then
        -- Restore: move out of the special workspace to the current normal one
        hl.dispatch(hl.dsp.window.move({ workspace = "+0" }))
        -- Hide the special workspace again if it's still open
        hl.dispatch(hl.dsp.workspace.toggle_special("minimize"))
    else
        -- Minimize: move silently so the special workspace doesn't pop open
        hl.dispatch(hl.dsp.window.move({ workspace = "special:minimize", follow = false }))
    end
end

-- Minimize / restore the focused window
hl.bind("SUPER + X", toggle_minimize)

-- Show/hide the minimized windows so you can pick one to restore
hl.bind("SUPER + SHIFT + X", function ()
    hl.dispatch(hl.dsp.workspace.toggle_special("minimize"))
end)