-- Auto-generated by DMS — do not edit manually

hl.env("HYPRCURSOR_THEME", "Future-black-cursors")
hl.env("XCURSOR_THEME", "Future-black-cursors")
hl.env("HYPRCURSOR_SIZE", "19")
hl.env("XCURSOR_SIZE", "19")

hl.config({
	cursor = {
		inactive_timeout = 1,
	},
})
