-- Auto-generated by DMS — do not edit manually

hl.monitor({ output = "eDP-1", mode = "1920x1080@60.008", position = "1920x0", scale = 1, vrr = 0, bitdepth = 10, cm = "hdr" })
hl.monitor({ output = "VGA-1", mode = "1920x1080@60.000", position = "0x0", scale = 1, vrr = 0 })
